sudo: false
language: cpp


script:

  - sudo apt install cmake
  - git clone --depth 1 https://github.com/google/googletest.git

  - cd googletest/
  - mkdir build
  - cd build
  - cmake -Dgtest_build_samples=ON -Dgtest_build_tests=ON ~/googletest
  - make
  - make test
  - ./googlemock/gtest/sample1_unittest
  - sudo cp -r -v ~/googletest/googletest/include/gtest /usr/local/include
  - sudo cp -r -v ~/googletest/googlemock/include/gmock /usr/local/include
  - sudo cp -v ~/googletest/build/googlemock/lib*.a /usr/local/lib
  - sudo cp -v ~/googletest/build/googlemock/gtest/lib*.a /usr/local/lib


  - cd ..
  - cd ..
  - ls -l
  - mkdir build
  - cd build/
  - g++ -std=c++11 ../src/main.cpp -o main
    #- g++ /usr/lib/libgtest.so /usr/lib/libgtest_main.so -lpthread -o main-ut ../tests/test_main.cpp
