sudo: false
language: cpp

script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd ..
  - sudo mkdir build
  - cd build/
  - sudo g++ -std=c++11 ../src/main.cpp -o main
  - sudo g++ /usr/lib/libgtest.so /usr/lib/libgtest_main.so -o main-ut ../tests/test_main.cpp

